/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsEvent {
  'userId' : [] | [UserId],
  'timestamp' : bigint,
  'details' : string,
  'eventType' : string,
}
export type AttemptId = bigint;
export interface BackupData {
  'categories' : Array<[bigint, Category]>,
  'userAnswers' : Array<[Principal, Array<UserAnswer>]>,
  'notifications' : Array<[bigint, Notification]>,
  'nextAttemptId' : AttemptId,
  'phoneToUserId' : Array<[string, UserId]>,
  'nextCategoryId' : CategoryId,
  'nextChapterId' : ChapterId,
  'chapters' : Array<[bigint, Chapter]>,
  'questions' : Array<[bigint, Question]>,
  'userExamResults' : Array<[UserId, Array<ExamResult>]>,
  'nextNotificationId' : NotificationId,
  'callerToUserId' : Array<[Principal, UserId]>,
  'userBookmarks' : Array<[Principal, Array<bigint>]>,
  'profiles' : Array<[Principal, UserProfile]>,
  'nextUserId' : UserId,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export type CategoryId = bigint;
export interface Chapter {
  'id' : ChapterId,
  'order' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'course' : string,
}
export type ChapterId = bigint;
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface ExamQuestionReview {
  'question' : Question,
  'userCorrect' : boolean,
  'correct' : boolean,
  'originalAnswer' : [] | [string],
  'selectedOption' : [] | [string],
}
export interface ExamResult {
  'questionReviews' : Array<ExamQuestionReview>,
  'attemptId' : AttemptId,
  'submitted' : boolean,
  'userId' : UserId,
  'answers' : Array<UserAnswer>,
  'score' : bigint,
  'timeRemaining' : bigint,
  'examType' : string,
  'passed' : boolean,
}
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'message' : string,
  'targetSegment' : string,
}
export type NotificationId = bigint;
export interface OtpVerifyResult { 'token' : string, 'isNew' : boolean }
export interface PracticeProgress {
  'totalAnswered' : bigint,
  'totalBookmarked' : bigint,
  'totalWrong' : bigint,
}
export interface Question {
  'id' : QuestionId,
  'question' : string,
  'hint' : string,
  'difficulty' : Difficulty,
  'explanation' : string,
  'createdAt' : bigint,
  'answer' : string,
  'course' : string,
  'chapter' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export type QuestionId = bigint;
export interface UserAnswer {
  'id' : bigint,
  'correct' : boolean,
  'timestamp' : bigint,
  'questionId' : QuestionId,
  'selectedOption' : string,
}
export type UserId = bigint;
export interface UserProfile {
  'userId' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
  'course' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnalyticsEvent' : ActorMethod<[string, [] | [UserId], string], undefined>,
  'addQuestion' : ActorMethod<
    [
      string,
      string,
      Difficulty,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backupData' : ActorMethod<[], BackupData>,
  'bulkUploadQuestions' : ActorMethod<[Array<Question>], bigint>,
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'createChapter' : ActorMethod<[string, string, bigint], bigint>,
  'createNotification' : ActorMethod<[string, string, string], bigint>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'exportUserResults' : ActorMethod<[], Array<[UserId, Array<ExamResult>]>>,
  'getAnalyticsEvents' : ActorMethod<[], Array<AnalyticsEvent>>,
  'getAttempts' : ActorMethod<[], Array<ExamResult>>,
  'getBookmarkedQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamModeReview' : ActorMethod<[], { 'examHistory' : Array<ExamResult> }>,
  'getExamQuestion' : ActorMethod<[bigint, bigint], ExamQuestionReview>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPracticeProgress' : ActorMethod<[string, string], PracticeProgress>,
  'getQuestions' : ActorMethod<
    [[] | [string], [] | [string], [] | [bigint], [] | [bigint]],
    Array<Question>
  >,
  'getUserExamHistory' : ActorMethod<[UserId], Array<ExamResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listChapters' : ActorMethod<[[] | [string]], Array<Chapter>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'restoreData' : ActorMethod<[BackupData], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [{ 'name' : string, 'phone' : string, 'course' : string }],
    undefined
  >,
  'searchQuestions' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [Difficulty],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Question>
  >,
  'sendOtp' : ActorMethod<[string], undefined>,
  'startExam' : ActorMethod<[string], bigint>,
  'submitAnswer' : ActorMethod<[bigint, string], boolean>,
  'submitExam' : ActorMethod<[bigint, Array<UserAnswer>], ExamResult>,
  'toggleBookmark' : ActorMethod<[bigint], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, string, string], undefined>,
  'updateChapter' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateQuestion' : ActorMethod<
    [
      bigint,
      string,
      string,
      Difficulty,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'verifyOtp' : ActorMethod<[string, string], OtpVerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];