/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const QuestionId = IDL.Nat;
export const UserAnswer = IDL.Record({
  'id' : IDL.Nat,
  'correct' : IDL.Bool,
  'timestamp' : IDL.Int,
  'questionId' : QuestionId,
  'selectedOption' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'message' : IDL.Text,
  'targetSegment' : IDL.Text,
});
export const AttemptId = IDL.Nat;
export const ChapterId = IDL.Nat;
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'course' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'question' : IDL.Text,
  'hint' : IDL.Text,
  'difficulty' : Difficulty,
  'explanation' : IDL.Text,
  'createdAt' : IDL.Int,
  'answer' : IDL.Text,
  'course' : IDL.Text,
  'chapter' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const ExamQuestionReview = IDL.Record({
  'question' : Question,
  'userCorrect' : IDL.Bool,
  'correct' : IDL.Bool,
  'originalAnswer' : IDL.Opt(IDL.Text),
  'selectedOption' : IDL.Opt(IDL.Text),
});
export const ExamResult = IDL.Record({
  'questionReviews' : IDL.Vec(ExamQuestionReview),
  'attemptId' : AttemptId,
  'submitted' : IDL.Bool,
  'userId' : UserId,
  'answers' : IDL.Vec(UserAnswer),
  'score' : IDL.Int,
  'timeRemaining' : IDL.Int,
  'examType' : IDL.Text,
  'passed' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const BackupData = IDL.Record({
  'categories' : IDL.Vec(IDL.Tuple(IDL.Nat, Category)),
  'userAnswers' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UserAnswer))),
  'notifications' : IDL.Vec(IDL.Tuple(IDL.Nat, Notification)),
  'nextAttemptId' : AttemptId,
  'phoneToUserId' : IDL.Vec(IDL.Tuple(IDL.Text, UserId)),
  'nextCategoryId' : CategoryId,
  'nextChapterId' : ChapterId,
  'chapters' : IDL.Vec(IDL.Tuple(IDL.Nat, Chapter)),
  'questions' : IDL.Vec(IDL.Tuple(IDL.Nat, Question)),
  'userExamResults' : IDL.Vec(IDL.Tuple(UserId, IDL.Vec(ExamResult))),
  'nextNotificationId' : NotificationId,
  'callerToUserId' : IDL.Vec(IDL.Tuple(IDL.Principal, UserId)),
  'userBookmarks' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat))),
  'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'nextUserId' : UserId,
});
export const AnalyticsEvent = IDL.Record({
  'userId' : IDL.Opt(UserId),
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'eventType' : IDL.Text,
});
export const PracticeProgress = IDL.Record({
  'totalAnswered' : IDL.Nat,
  'totalBookmarked' : IDL.Nat,
  'totalWrong' : IDL.Nat,
});
export const OtpVerifyResult = IDL.Record({
  'token' : IDL.Text,
  'isNew' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnalyticsEvent' : IDL.Func([IDL.Text, IDL.Opt(UserId), IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Difficulty,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backupData' : IDL.Func([], [BackupData], ['query']),
  'bulkUploadQuestions' : IDL.Func([IDL.Vec(Question)], [IDL.Nat], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'createChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'exportUserResults' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, IDL.Vec(ExamResult)))],
      ['query'],
    ),
  'getAnalyticsEvents' : IDL.Func([], [IDL.Vec(AnalyticsEvent)], ['query']),
  'getAttempts' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
  'getBookmarkedQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamModeReview' : IDL.Func(
      [],
      [IDL.Record({ 'examHistory' : IDL.Vec(ExamResult) })],
      ['query'],
    ),
  'getExamQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [ExamQuestionReview],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPracticeProgress' : IDL.Func(
      [IDL.Text, IDL.Text],
      [PracticeProgress],
      ['query'],
    ),
  'getQuestions' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserExamHistory' : IDL.Func([UserId], [IDL.Vec(ExamResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listChapters' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Chapter)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'restoreData' : IDL.Func([BackupData], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'phone' : IDL.Text,
          'course' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'searchQuestions' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Difficulty),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'sendOtp' : IDL.Func([IDL.Text], [], []),
  'startExam' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'submitExam' : IDL.Func([IDL.Nat, IDL.Vec(UserAnswer)], [ExamResult], []),
  'toggleBookmark' : IDL.Func([IDL.Nat], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
  'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Difficulty,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [OtpVerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const QuestionId = IDL.Nat;
  const UserAnswer = IDL.Record({
    'id' : IDL.Nat,
    'correct' : IDL.Bool,
    'timestamp' : IDL.Int,
    'questionId' : QuestionId,
    'selectedOption' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'message' : IDL.Text,
    'targetSegment' : IDL.Text,
  });
  const AttemptId = IDL.Nat;
  const ChapterId = IDL.Nat;
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'course' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'question' : IDL.Text,
    'hint' : IDL.Text,
    'difficulty' : Difficulty,
    'explanation' : IDL.Text,
    'createdAt' : IDL.Int,
    'answer' : IDL.Text,
    'course' : IDL.Text,
    'chapter' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const ExamQuestionReview = IDL.Record({
    'question' : Question,
    'userCorrect' : IDL.Bool,
    'correct' : IDL.Bool,
    'originalAnswer' : IDL.Opt(IDL.Text),
    'selectedOption' : IDL.Opt(IDL.Text),
  });
  const ExamResult = IDL.Record({
    'questionReviews' : IDL.Vec(ExamQuestionReview),
    'attemptId' : AttemptId,
    'submitted' : IDL.Bool,
    'userId' : UserId,
    'answers' : IDL.Vec(UserAnswer),
    'score' : IDL.Int,
    'timeRemaining' : IDL.Int,
    'examType' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const BackupData = IDL.Record({
    'categories' : IDL.Vec(IDL.Tuple(IDL.Nat, Category)),
    'userAnswers' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(UserAnswer))),
    'notifications' : IDL.Vec(IDL.Tuple(IDL.Nat, Notification)),
    'nextAttemptId' : AttemptId,
    'phoneToUserId' : IDL.Vec(IDL.Tuple(IDL.Text, UserId)),
    'nextCategoryId' : CategoryId,
    'nextChapterId' : ChapterId,
    'chapters' : IDL.Vec(IDL.Tuple(IDL.Nat, Chapter)),
    'questions' : IDL.Vec(IDL.Tuple(IDL.Nat, Question)),
    'userExamResults' : IDL.Vec(IDL.Tuple(UserId, IDL.Vec(ExamResult))),
    'nextNotificationId' : NotificationId,
    'callerToUserId' : IDL.Vec(IDL.Tuple(IDL.Principal, UserId)),
    'userBookmarks' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat))),
    'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'nextUserId' : UserId,
  });
  const AnalyticsEvent = IDL.Record({
    'userId' : IDL.Opt(UserId),
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const PracticeProgress = IDL.Record({
    'totalAnswered' : IDL.Nat,
    'totalBookmarked' : IDL.Nat,
    'totalWrong' : IDL.Nat,
  });
  const OtpVerifyResult = IDL.Record({
    'token' : IDL.Text,
    'isNew' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnalyticsEvent' : IDL.Func(
        [IDL.Text, IDL.Opt(UserId), IDL.Text],
        [],
        [],
      ),
    'addQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Difficulty,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backupData' : IDL.Func([], [BackupData], ['query']),
    'bulkUploadQuestions' : IDL.Func([IDL.Vec(Question)], [IDL.Nat], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'createChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'exportUserResults' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, IDL.Vec(ExamResult)))],
        ['query'],
      ),
    'getAnalyticsEvents' : IDL.Func([], [IDL.Vec(AnalyticsEvent)], ['query']),
    'getAttempts' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
    'getBookmarkedQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamModeReview' : IDL.Func(
        [],
        [IDL.Record({ 'examHistory' : IDL.Vec(ExamResult) })],
        ['query'],
      ),
    'getExamQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [ExamQuestionReview],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPracticeProgress' : IDL.Func(
        [IDL.Text, IDL.Text],
        [PracticeProgress],
        ['query'],
      ),
    'getQuestions' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserExamHistory' : IDL.Func([UserId], [IDL.Vec(ExamResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listChapters' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'restoreData' : IDL.Func([BackupData], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'phone' : IDL.Text,
            'course' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'searchQuestions' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Difficulty),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'sendOtp' : IDL.Func([IDL.Text], [], []),
    'startExam' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'submitExam' : IDL.Func([IDL.Nat, IDL.Vec(UserAnswer)], [ExamResult], []),
    'toggleBookmark' : IDL.Func([IDL.Nat], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
    'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Difficulty,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [OtpVerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };